services:

  server_py:
    image: z53_server_abp_py_image
    build: ./server
    container_name: z53_udp_abp_server_py
    networks:
      z53_network:
        ipv6_address: fd00:1032:ac21:53::2
    tty: true
    cap_add:
      - NET_ADMIN

  client_c:
    image: z53_client_abp_c_image
    build: ./client
    container_name: z53_udp_abp_client_c
    networks:
      z53_network:
        ipv6_address: fd00:1032:ac21:53::3
    tty: true
    cap_add:
      - NET_ADMIN
    depends_on:
      - server_py
    command: ["./client", "fd00:1032:ac21:53::2"]

networks:
  z53_network:
    external: true
    name: z53_network